### ISSUE TITLE
Add quotes to example SQL insert

### ISSUE THREAD

**Issue by jdavidpeery** [ag-informatics/ag-informatics-course#47]
In Lab 3, the first SQL insert statement is the following - 

insert into crops (crop_name, maturity_date)
values (carrot, 70);

which I believe? should be changed to - 

insert into crops (crop_name, maturity_date)
values ('carrot', 70);

, adding single quotes around carrot, otherwise it didn't work on my MacOS SQLite3

**Comment by jdavidpeery** [comment]
@tame0001

**Comment by tame0001** [comment]
It should have quote. My mistake. Fixed.
